web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - redis

db:
  image: postgres
  volumes_from:
    - pg_data

redis:
  image: redis

pg_data:
  image: pg_data
