# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20161120_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-pk'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['-pk'], 'verbose_name': 'Reviewer', 'verbose_name_plural': 'Reviewers'},
        ),
    ]
