# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20161120_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[reviews.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.TextField(max_length=10000, validators=[reviews.models.validate_summary]),
        ),
    ]
