# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20161120_0428'),
        ('reviews', '0005_auto_20161120_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='oauth.Client'),
            preserve_default=False,
        ),
    ]
